### ISSUE TITLE
Need a function to confirm the operation to telegram-bot is from localhost.

### ISSUE THREAD

**Issue by asas1asas200** [MadRex2000/ntou2.0#17]
Cannot use "request.remote_addr", because of the "stunnel" made all of the data be "127.0.0.1".
Need a new function or token to do this, otherwise anyone can post fake data to operate.

**Comment by MadRex2000** [comment]
Actually I don't understand what you mean.
Can you say it again and deliver clearly.

**Comment by asas1asas200** [comment]
I can post data from my computer to control the telegram-bot, but it should only be operated by server.

**Comment by MadRex2000** [comment]
Ok I see that problem I think TBD.
It will be solved before the service officially online.
